targetNamespace: ''
parameters: {}
packages:
  - name: oauth
    environment:
      OAUTH_CLIENT_ID: ${OAUTH_CLIENT_ID}
      OAUTH_CLIENT_SECRET: ${OAUTH_CLIENT_SECRET}
    functions:
      - name: auth
        binary: false
        main: ''
        runtime: 'nodejs:18'
        web: true
      - name: callback
        binary: false
        main: ''
        runtime: 'nodejs:18'
        web: true
  - name: mailer
    environment:
      SMTP_HOST: ${SMTP_HOST}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASS: ${EMAIL_PASS}
      NOTIFICATION_EMAIL: ${NOTIFICATION_EMAIL}
    functions:
      - name: __main__
        binary: false
        main: ''
        runtime: 'python:3.9'
        web: true
        methods:
          - POST